services:
  wis:
    restart: unless-stopped
    image: willow-inference-server:latest
    env_file:
      - .env
    shm_size: '1gb'
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    #build:
    #  dockerfile: Dockerfile
    ports:
      - ${MEDIA_PORT_RANGE}:${MEDIA_PORT_RANGE}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    volumes:
      - ./:/app
    command: ./entrypoint.sh

  web:
    restart: unless-stopped
    image: nginx
    shm_size: '1gb'
    volumes:
    - ./nginx:/nginx
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
    - "80:80"
    - "443:443"